
name: Pytest

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  job:
    name: My job
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7",  "3.8", "3.9", "3.10" ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev --python ${{ matrix.python-version }}
    - name: Test with pytest
      run: |
        pipenv run pytest -v
